# se creo el archivo: 
# cat /etc/launchd.conf
# limit maxproc 1024 2048
# despues de ejecutar:
# launchctl limit
# 
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
./pide.sh $1 &
